---
title: "Week 40"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.path = "README_figs/README-")
```


 Libraries and settings
```{r results='hide', message=FALSE, warning=FALSE}
library(tidyverse)
library(tidytuesdayR)

```
# Load the weekly Data

Dowload the weekly data and make available in the `tt` object.
```{r  results='hide', message=FALSE, warning=FALSE}
#data <- tidytuesdayR::tt_load('2020-09-29')

charts<-readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-29/charts.csv")
taylor_swift_lyrics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-29/taylor_swift_lyrics.csv') %>% 
  mutate(Lyrics=tolower(Lyrics))

```
# Readme

Take a look at the readme for the weekly data to get insight on the dataset.
This includes a data dictionary, source, and a link to an article on the data.

```{r Readme, eval = interactive()}
taylor_swift_lyrics 

```


# Visualize

Using your processed dataset, create your unique visualization.

```{r Visualize}
df <- taylor_swift_lyrics %>%
  group_by(Album) %>% 
  summarize(love_count = sum(str_count(Lyrics, "love"))) %>% 
  mutate(Album=factor(Album,ordered = TRUE, levels = c("Taylor Swift", "Fearless", "Speak Now", "Red", "1989", "reputation", "Lover", "folklore")))

plot<-ggplot(df, aes(x = Album, y = love_count)) +
  geom_segment(aes(x = Album, xend = Album, y = 0, yend = love_count), size = 1.5, color = "#CF2F2C", linetype="dotdash")+
  geom_point(size = 7.5, color ="#D05DD4" , shape="\U2665")+ 
  scale_y_continuous(breaks = seq(0, 90, by = 10))+
  coord_flip()+
  theme(
    plot.background = element_rect( fill = "#423F3F"),
    panel.background = element_rect( fill = "#423F3F"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(size = 3, colour = "grey80"),
    axis.ticks = element_blank(),
    plot.title = element_text(size = 20, hjust = .4, color = "#ad3b70", face = "bold"),
    plot.subtitle = element_text(size = 13.5, hjust = .4, color = "#ad3b70"),
    axis.text.y = element_text(size = 12, face = "bold", color = "#519bc9", margin = margin(r=0)),
    axis.title = element_text(size = 14, color = "#ad3b70"),
    axis.text.x = element_text(size = 12, face = "bold", color = "#ad3b70"),
    plot.caption=element_text(size = 10,color ="#D05DD4")
  )+
  labs(
    x = "Album",
    y = "",
    title = "Taylor Swift's Use of Love",
    subtitle = "Lyrical occurences of 'love' across albums",
    caption = "Source: Beyoncé and Taylor Swift Lyrics \nTidyTuesday Project - week 40 \n Visualization: @Lacapary")
  
  
```

#Plot

```{r echo = FALSE}

plot

```

  